version: "3"
services:
  user-service:
    build: ./pkg/user/
    image: user-service
    environment:
      USER_SERVICE_PORT: 8082
    ports:
      - 8082:8082
  
  auth-service:
    build: ./pkg/auth/
    image: auth-service
    environment:
      AUTH_SERVICE_PORT: 8083
      USER_SERVICE_PORT: 8082
      USER_SERVICE_HOST: localhost
      USER_SERVICE_PORT: 8082
    ports:
      - 8083:8083
    depends_on:
      - user-service